### ISSUE TITLE
Persistir los datos de las cantidades cuando se recarga la pagina del carrito

### ISSUE THREAD

**Issue by deyvisenrique** [deyvisenrique/senati#12]
Trabajar este requerimiento solo en la sección Shop / Cart Page 4

Actualmente cuando se cambian las cantidades en los productos y luego se recarga la pagina se pierden los valores originales.
Se necesita mantener las cantidades de los productos segun el usuario las modifique. Y si la pagina se recarga debe mostrar la ultima modificación del usuario. 
Para esto puedo ayudarse del localStorage y sessionStorage

<img width="1356" alt="Screen Shot 2022-10-18 at 13 04 38" src="https://user-images.githubusercontent.com/15927272/196512001-1c29565f-1406-41b0-b6d1-c4e98ac14077.png">

**Comment by rayvega20** [comment]
vega
