### ISSUE TITLE
Guardar los datos del formulario en una base de datos dentro del hosting

### ISSUE THREAD

**Issue by deyvisenrique** [deyvisenrique/senati#2]
Actualmente el formulario no guarda en ningun lado la información que se rellena.

El formulario donde se implementara este issue se encuentra en el menu: contact / contact 2

Se desea implementar un archivo PHP que procese esta información y la guarde en una base de datos dentro del hosting con las siguiente pautas:
- Debe crear una base de datos exclusiva para guardar esta información.
- Debe haber una columna adicional que registre la fecha en que se envia el formulario.

**Comment by TrinidadRS** [comment]
terminado
