### ISSUE TITLE
Personalizar algunas secciones de la pagina de inicio con el nombre del visitante.

### ISSUE THREAD

**Issue by deyvisenrique** [deyvisenrique/senati#5]
Trabajar este requerimiento solo en la sección Home / MultiPage / Web Design

Cuando la pagina carga por primera ves debe aparecer un modal preguntando el nombre del cliente y debe haber un campo para que el usuario escriba su nombre.. luego este nombre debe aparecer en los siguientes lugares:

Se dan un ejemplo con el Nombre Daniel:

<img width="1444" alt="Screen Shot 2022-10-16 at 20 16 28" src="https://user-images.githubusercontent.com/15927272/196070596-5243345e-3227-4111-8b59-221325fa626f.png">
<img width="884" alt="Screen Shot 2022-10-16 at 20 18 08" src="https://user-images.githubusercontent.com/15927272/196070615-a6e86bd1-d967-47d8-b1f2-ec9bcf2888de.png">
<img width="1381" alt="Screen Shot 2022-10-16 at 20 27 02" src="https://user-images.githubusercontent.com/15927272/196070618-6f2f7643-476f-431a-8cb5-3294d13c72e6.png">

**Comment by MiguelPacco** [comment]
Ventana modal, agregada

**Comment by MiguelPacco** [comment]
Terminado.
