### ISSUE TITLE
Habilitar el cupón de descuento y aplicarlo al total en la pagina del carrito

### ISSUE THREAD

**Issue by deyvisenrique** [deyvisenrique/senati#9]
Trabajar este requerimiento solo en la sección Shop / Cart Page 1

Se requiere que el campo de cupón de descuento pueda funcionar y se aplique el descuento al total tal como se muestra en la imagen de abajo.

Adicionalmente se quiere para esta primera etapa la creación de 3 cupones
1. Nombre de cupón: FERIADO por un valor fijo 30
2. Nombre de cupón: DIAS-RR por un valor fijo 33
3. Nombre de cupón: BIENVENIDO por un valor porcentual de 10% (Quiere decir que se aplicara un descuento del 10%)

<img width="1400" alt="Screen Shot 2022-10-18 at 12 30 15" src="https://user-images.githubusercontent.com/15927272/196505952-409e583d-fb1c-4013-9a75-33a95424e3d2.png">

**Comment by BillySamObregonVelasquez** [comment]
issue TERMINADO 

Archivo creado/modificado 
   cupon.js (creado)
  cart1.html (modificado)


Claves de cupón
   FERIADO por un valor fijo 30
   DIAS-RR por un valor fijo 33
   BIENVENIDO por un valor porcentual de 10% (Quiere decir que se aplicara un descuento del 10%)
